# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
print(random_tensor)
random_tensor.shape

tensor([[0.9576, 0.7727, 0.4881, 0.4978, 0.1737, 0.4223, 0.3015],
        [0.2831, 0.6477, 0.9857, 0.3577, 0.1754, 0.6629, 0.9047],
        [0.1608, 0.7519, 0.7512, 0.8314, 0.6952, 0.7374, 0.3911],
        [0.2862, 0.5887, 0.3899, 0.8476, 0.6614, 0.6213, 0.2762],
        [0.3258, 0.1551, 0.9069, 0.5694, 0.1824, 0.9428, 0.8361],
        [0.6066, 0.9276, 0.7374, 0.9405, 0.9821, 0.0723, 0.3432],
        [0.6042, 0.4347, 0.0760, 0.1228, 0.7456, 0.5200, 0.8820]])


torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
random_tensor2 = torch.rand(size=(1,7))

# Perform matrix multiplication 
torch.matmul(random_tensor , random_tensor2.T)

tensor([[2.3225],
        [2.6142],
        [2.8902],
        [2.4122],
        [2.4422],
        [3.4452],
        [1.9436]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))

# Matrix multiply tensors
tensor3 = torch.matmul(tensor , tensor2.T)
print(tensor3 , tensor3.shape)



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
tensor = torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [36]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU

# Create two random tensors on GPU
tensor = torch.rand(3,2 , device='cuda')
tensor2 = torch.rand(3,2 , device='cuda')

tensor , tensor2

(tensor([[0.1272, 0.8167],
         [0.5440, 0.6601],
         [0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276],
         [0.3255, 0.1114],
         [0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
# Perform matmul on tensor_A and tensor_B
tensor3 = torch.matmul(tensor.T , tensor2)
print(tensor3 , tensor3.shape)

tensor([[0.4414, 0.1623],
        [1.3852, 0.4474]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [40]:
# Find max
print(f"Max = {tensor3.max()}")
# Find min
print(f'Min = {tensor3.min()}')


Max = 1.385164737701416
Min = 0.16229058802127838


### 9. Find the maximum and minimum index values of the output of 7.

In [42]:
# Find arg max
print(tensor3.argmax())

# Find arg min
print(tensor3.argmin())

tensor(2, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [46]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tenosr2 = tensor.squeeze()

# Print out tensors and their shapes
print(tensor , tensor.shape)
print(tensor2 , tenosr2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([[0.6208, 0.0276],
        [0.3255, 0.1114],
        [0.6812, 0.3608]], device='cuda:0') torch.Size([10])
